import { SETTINGS } from "./settings";

export const _ST = {
  CID: SETTINGS.CONTEST_ID,
  PCS: SETTINGS.PROBLEM_COLORS as {[key: string]: string},

  PD: SETTINGS.PROBLEM_POINTS,
  USE_PD: SETTINGS.CUSTOM_POINT_VALUES,

  ACC: SETTINGS.ACCEPTED_COLOR,
  TTC: SETTINGS.TESTING_COLOR,
  RJC: SETTINGS.REJECTED_COLOR,
  FZC: SETTINGS.FROZEN_COLOR,

  FZ: SETTINGS.FREEZEAT_SECONDS,

  MXSMD: SETTINGS.MAX_SUBMISSIONS_DISPLAYED,
  MXSTD: SETTINGS.MAX_STANDINGS_DISPLAYED,

  SNRIMS: SETTINGS.QUEUE_RELOAD_INTERVAL_MS,
  STRIMS: SETTINGS.STANDINGS_RELOAD_INTERVAL_MS,

  STATUS_PATH: SETTINGS.QUEUE_PATH,
  STANDINGS_PATH: SETTINGS.STANDINGS_PATH,

  SUO: SETTINGS.SHOW_UNOFFICIAL,

  PORT: SETTINGS.PORT,
};
