import { SETTINGS } from "./settings";

export const _ST = {
  CID: SETTINGS.CONTEST_ID,
  PCS: SETTINGS.PROBLEM_COLORS as {[key: string]: string},

  ACC: SETTINGS.ACCEPTED_COLOR,
  TTC: SETTINGS.TESTING_COLOR,
  RJC: SETTINGS.REJECTED_COLOR,

  MXSMD: SETTINGS.MAX_SUBMISSIONS_DISPLAYED,
  MXSTD: SETTINGS.MAX_STANDINGS_DISPLAYED,

  STRIMS: SETTINGS.QUEUE_RELOAD_INTERVAL_MS,
  SNRIMS: SETTINGS.STANDINGS_RELOAD_INTERVAL_MS,

  STATUS_PATH: SETTINGS.QUEUE_PATH,
  STANDINGS_PATH: SETTINGS.STANDINGS_PATH,

  PORT: SETTINGS.PORT,
};
